import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TopNav from "@/components/common/TopNav";
import Footer from "@/components/common/Footer";
import { ModalProvider } from "@/context/ModalContext";
import { Toaster } from "react-hot-toast";
import { AuthProvider } from "@/context/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <ModalProvider>
            <TopNav />
            <div className="min-h-screen bg-gradient-to-b from-red-500 to-white">
              {children}
            </div>
            <Toaster
              position="top-right"
              toastOptions={{
                success: {
                  style: {
                    background: "#22c55e", // Tailwind green-500
                    color: "white",
                  },
                },
                error: {
                  style: {
                    background: "#ef4444", // Tailwind red-500
                    color: "white",
                  },
                },
                loading: {
                  style: {
                    background: "#f97316", // Tailwind orange-500 (for warning/processing)
                    color: "white",
                  },
                },
              }}
            />
            <Footer />
          </ModalProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
