import type { Metadata } from "next";
import { Merriweather } from "next/font/google";
import "./globals.css";
import TopNav from "@/components/common/TopNav";
import Footer from "@/components/common/Footer";
import { ModalProvider } from "@/context/ModalContext";
import { Toaster } from "react-hot-toast";
import { AuthProvider } from "@/context/AuthContext";
import { CartProvider } from "@/components/order/CartProvider";

const merriweather = Merriweather({
  subsets: ["latin"],
  weight: ["300", "400", "700", "900"],
  variable: "--font-merriweather",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${merriweather.variable} antialiased`}>
        <AuthProvider>
          <CartProvider>
            <ModalProvider>
              <TopNav />
              <div className="min-h-screen bg-gradient-to-b from-red-500 to-white">
                {children}
              </div>
              <Toaster
                position="top-right"
                toastOptions={{
                  success: {
                    style: {
                      background: "#22c55e",
                      color: "white",
                    },
                  },
                  error: {
                    style: {
                      background: "#ef4444",
                      color: "white",
                    },
                  },
                  loading: {
                    style: {
                      background: "#f97316",
                      color: "white",
                    },
                  },
                }}
              />
              <Footer />
            </ModalProvider>
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
